[package]
name = "merand48"
version = "0.1.0"
authors = ["Jack Gerrits <jackgerrits95@gmail.com>"]
edition = "2018"
repository = "https://github.com/jackgerrits/merand48-rs"
description = "Quick random number generator used in VowpalWabbit"
license = "BSD-3-Clause"

[dependencies]
